Feature/DE-2
github-engineering-tool/data-extractor pull request #6
Opened 2021-08-13 04:31 UTC by shashankbaranwal

2021-08-15 20:34 UTC, Nikhil-Rawat commented
1. Use lowercase on the commit messagea.

2021-08-17 10:43 UTC, shashankbaranwal commented on src/repositories/organization/IOrganizationDocument.ts
> +  members: IMember;
Resolve Both Point:-
1. Add member in the array.
2. Add repository in the array.

2021-08-17 10:43 UTC, shashankbaranwal commented on src/repositories/organization/IOrganizationDocument.ts
> +  permission: {
We will be created interface for permission.

2021-08-17 10:44 UTC, shashankbaranwal commented on src/repositories/organization/OrganizationSchema.ts
> +  userName: {
Resolve it.

2021-08-17 10:53 UTC, shashankbaranwal commented on src/repositories/versionable/IDocument.ts
> +
Resolve it.

2021-08-17 10:58 UTC, shashankbaranwal commented on src/repositories/organization/OrganizationSchema.ts
> +const Collaborator = new Schema({
Resolve it.

2021-08-17 18:32 UTC, shashankbaranwal commented on src/repositories/organization/OrganizationSchema.ts
> +const Permission = new Schema({
Resolve it

2021-08-17 18:32 UTC, shashankbaranwal commented on src/repositories/organization/OrganizationSchema.ts
> +const Collaborator = new Schema({
Resolve it

2021-08-17 18:32 UTC, shashankbaranwal commented on src/repositories/organization/OrganizationSchema.ts
> +import VersionableSchema from "../versionable/Schema";
Resolve it

2021-08-19 12:39 UTC, barkhatyagi commented on src/repositories/organization/OrganizationRepository.ts
> +    const id = UserRepository.generateObjectId();
add interface of data

2021-08-19 12:48 UTC, Nikhil-Rawat requested changes
add comment

2021-08-19 12:50 UTC, Nikhil-Rawat approved these changes

2021-08-19 12:52 UTC, Nikhil-Rawat approved these changes

2021-08-19 12:52 UTC, Nikhil-Rawat approved these changes

2021-08-19 13:11 UTC, Nikhil-Rawat approved these changes

2021-08-19 13:13 UTC, barkhatyagi approved these changes

2021-08-19 13:14 UTC, merged